// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxrZkrZqpcgWUAtYOjQQhdqmgcCDXoXNQ',
    appId: '1:202938428340:android:9bbe0c21811be7294de0e1',
    messagingSenderId: '202938428340',
    projectId: 'flutter-77239',
    storageBucket: 'flutter-77239.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8KPEx4wSaspEb6m7WNuXt5ME_-KD5as8',
    appId: '1:202938428340:ios:3d9ccda958213ebe4de0e1',
    messagingSenderId: '202938428340',
    projectId: 'flutter-77239',
    storageBucket: 'flutter-77239.appspot.com',
    iosClientId: '202938428340-4nhc1jh0iosb746pe0l6gv9hv0nb6cje.apps.googleusercontent.com',
    iosBundleId: 'intern.tsp.myflu',
  );
}
